import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createTeacherApi, type Assignment, type AssignmentInput, type ClassInput } from "./teacher-api";
import type { AccessTokenProvider, ApiError } from "../../lib/api-client";

type Route = { page: "dashboard" | "new-class" } | { page: "class" | "new-assignment"; classId: string } | { page: "assignment"; assignmentId: string };
const routeFor = (): Route => {
  const parts = location.hash.replace(/^#\//, "").split("/");
  if (parts[0] === "classes" && parts[2] === "assignments" && parts[3] === "new") return { page: "new-assignment", classId: parts[1] };
  if (parts[0] === "classes" && parts[1]) return { page: "class", classId: parts[1] };
  if (parts[0] === "assignments" && parts[1]) return { page: "assignment", assignmentId: parts[1] };
  return parts[0] === "classes" && parts[1] === "new" ? { page: "new-class" } : { page: "dashboard" };
};
const go = (path: string) => { location.hash = path; };
const message = (reason: unknown) => {
  const error = reason as ApiError;
  return `${error.code ? `[${error.code}] ` : ""}${error.message ?? "Something went wrong."}${error.requestId ? ` (Support ID: ${error.requestId})` : ""}`;
};
const date = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not submitted";

function useResource<T>(load: () => Promise<T>, key: string) {
  const [data, setData] = useState<T>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true);
  const reload = useCallback(() => { setLoading(true); setError(undefined); void load().then(setData).catch((e) => setError(message(e))).finally(() => setLoading(false)); }, [load]);
  useEffect(reload, [reload, key]);
  return { data, error, loading, reload };
}

function Notice({ error }: { error?: string }) { return error ? <p className="notice" role="alert">{error}</p> : null; }
function Loading() { return <p className="muted">Loading…</p>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="empty">{children}</p>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function AssignmentForm({ initial, onSubmit, saving }: { initial?: Assignment; onSubmit: (value: AssignmentInput) => void; saving: boolean }) {
  return <form className="form" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); onSubmit({ title: String(f.get("title")), topic: String(f.get("topic")), learning_objective: String(f.get("learning_objective")), grade_level: String(f.get("grade_level")), instructions: String(f.get("instructions")), sandbox_type: "parameter_explorer" }); }}>
    <Field label="Assignment title"><input name="title" required defaultValue={initial?.title} /></Field><Field label="Lesson topic"><input name="topic" required defaultValue={initial?.topic} /></Field><Field label="Learning objective"><textarea name="learning_objective" required defaultValue={initial?.learning_objective} /></Field><Field label="Grade level"><input name="grade_level" required defaultValue={initial?.grade_level} /></Field><Field label="Teacher instructions"><textarea name="instructions" defaultValue={initial?.instructions ?? ""} /></Field><Field label="Sandbox type"><input value="Parameter explorer" disabled /><small>Only the supported MVP sandbox is available.</small></Field><button disabled={saving}>{saving ? "Saving…" : "Save draft"}</button>
  </form>;
}

export function TeacherApp({ getAccessToken, onSignOut }: { getAccessToken: AccessTokenProvider; onSignOut: () => Promise<unknown> }) {
  const api = useMemo(() => createTeacherApi(getAccessToken), [getAccessToken]);
  const [route, setRoute] = useState(routeFor()); const [signedOut, setSignedOut] = useState(false);
  useEffect(() => { const update = () => setRoute(routeFor()); addEventListener("hashchange", update); return () => removeEventListener("hashchange", update); }, []);
  const profile = useResource(api.me, "profile");
  async function logout() { await onSignOut(); setSignedOut(true); }
  if (signedOut) return <main className="auth"><h1>Prism</h1><p>You have signed out.</p><p className="muted">Sign in through the shared authentication screen to continue.</p></main>;
  if (profile.loading) return <main className="shell"><Loading /></main>;
  if (profile.error?.includes("PROFILE_NOT_PROVISIONED")) return <Bootstrap api={api} />;
  if (profile.error) return <main className="auth"><h1>Teacher sign in</h1><Notice error={profile.error} /><p className="muted">Sign in through the shared Clerk authentication screen, then return here.</p></main>;
  if (profile.data?.role !== "teacher") return <main className="auth"><h1>Teacher access only</h1><p>Your current profile is not a teacher profile.</p></main>;
  return <main className="shell"><header><a className="brand" href="#/">Prism</a><span>{profile.data.display_name}</span><button className="link" onClick={() => void logout()}>Log out</button></header>{route.page === "dashboard" && <Dashboard api={api} />}{route.page === "new-class" && <NewClass api={api} />}{route.page === "class" && <ClassPage api={api} classId={route.classId} />}{route.page === "new-assignment" && <NewAssignment api={api} classId={route.classId} />}{route.page === "assignment" && <AssignmentPage api={api} assignmentId={route.assignmentId} />}</main>;
}

function TeacherPreview() {
  return <main className="shell"><header><a className="brand" href="#/">Prism</a><span>Teacher preview</span></header><section><div className="page-heading"><div><h1>Your classes</h1><p>Manage classes and assignment drafts.</p></div><button type="button">Create class</button></div><p className="notice">Preview mode — connect the shared Clerk auth client to use live data.</p><div className="cards"><article className="card"><h2>Physics 101</h2><p>Physics · Grade 10</p><p className="muted">3 students · 1 assignment</p><button className="secondary" type="button">Open class</button></article></div></section></main>;
}

function Bootstrap({ api }: { api: ReturnType<typeof createTeacherApi> }) { const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false); return <main className="auth"><h1>Set up your teacher profile</h1><form className="form" onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSaving(true); void api.bootstrap(String(new FormData(e.currentTarget).get("name"))).then(() => location.reload()).catch((r) => setError(message(r))).finally(() => setSaving(false)); }}><Notice error={error}/><Field label="Display name"><input name="name" required /></Field><button disabled={saving}>{saving ? "Saving…" : "Continue"}</button></form></main>; }
function Dashboard({ api }: { api: ReturnType<typeof createTeacherApi> }) { const r = useResource(api.classes, "classes"); return <section><div className="page-heading"><div><h1>Your classes</h1><p>Manage classes and assignment drafts.</p></div><button onClick={() => go("/classes/new")}>Create class</button></div><Notice error={r.error}/>{r.loading ? <Loading/> : r.data?.items.length ? <div className="cards">{r.data.items.map((c) => <article className="card" key={c.id}><h2>{c.name}</h2><p>{c.subject} · Grade {c.grade_level}</p><p className="muted">{c.student_count} students · {c.assignment_count} assignments</p><button className="secondary" onClick={() => go(`/classes/${c.id}`)}>Open class</button></article>)}</div> : <Empty>Create a class to get started.</Empty>}</section>; }
function NewClass({ api }: { api: ReturnType<typeof createTeacherApi> }) { const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false); return <section><div className="page-heading"><h1>Create class</h1></div><form className="form" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const value: ClassInput = { name: String(f.get("name")), subject: String(f.get("subject")), grade_level: String(f.get("grade_level")), description: String(f.get("description")) }; setSaving(true); void api.createClass(value).then((c) => go(`/classes/${c.id}`)).catch((r) => setError(message(r))).finally(() => setSaving(false)); }}><Notice error={error}/><Field label="Class name"><input name="name" required/></Field><Field label="Subject"><input name="subject" required/></Field><Field label="Grade level"><input name="grade_level" required/></Field><Field label="Description"><textarea name="description"/></Field><button disabled={saving}>{saving ? "Creating…" : "Create class"}</button></form></section>; }
function ClassPage({ api, classId }: { api: ReturnType<typeof createTeacherApi>; classId: string }) { const c = useResource(() => api.classDetail(classId), `class-${classId}`); const members = useResource(() => api.members(classId), `members-${classId}`); const assignments = useResource(() => api.assignments(classId), `assignments-${classId}`); if (c.loading) return <Loading/>; if (!c.data) return <Notice error={c.error}/>; return <section><div className="page-heading"><div><a href="#/">← Classes</a><h1>{c.data.name}</h1><p>{c.data.subject} · Grade {c.data.grade_level}</p></div><button onClick={() => go(`/classes/${classId}/assignments/new`)}>Create assignment</button></div><p>{c.data.description || "No description provided."}</p><div className="join-code"><span>Student join code</span><strong>{c.data.join_code}</strong><button className="secondary" onClick={() => void navigator.clipboard?.writeText(c.data!.join_code)}>Copy</button></div><div className="two-col"><section><h2>Students ({members.data?.total ?? 0})</h2><Notice error={members.error}/>{members.loading ? <Loading/> : members.data?.items.length ? <ul>{members.data.items.map((m) => <li key={m.student_id}>{m.display_name}<span>{date(m.joined_at)}</span></li>)}</ul> : <Empty>No students have joined yet.</Empty>}</section><section><h2>Assignments ({assignments.data?.total ?? 0})</h2><Notice error={assignments.error}/>{assignments.loading ? <Loading/> : assignments.data?.items.length ? <ul>{assignments.data.items.map((a) => <li key={a.id}><button className="link" onClick={() => go(`/assignments/${a.id}`)}>{a.title}</button><span className="badge">{a.status}</span></li>)}</ul> : <Empty>No assignments yet.</Empty>}</section></div></section>; }
function NewAssignment({ api, classId }: { api: ReturnType<typeof createTeacherApi>; classId: string }) { const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false); return <section><div className="page-heading"><h1>Create assignment</h1></div><Notice error={error}/><AssignmentForm saving={saving} onSubmit={(value) => { setSaving(true); void api.createAssignment(classId, value).then((a) => go(`/assignments/${a.id}`)).catch((r) => setError(message(r))).finally(() => setSaving(false)); }}/></section>; }
function AssignmentPage({ api, assignmentId }: { api: ReturnType<typeof createTeacherApi>; assignmentId: string }) { const r = useResource(() => api.assignment(assignmentId), `assignment-${assignmentId}`); const submissions = useResource(() => api.submissions(assignmentId), `submissions-${assignmentId}`); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>(); if (r.loading) return <Loading/>; const a = r.data; if (!a) return <Notice error={r.error}/>; const save = (value: AssignmentInput) => { setSaving(true); void api.updateAssignment(a.id, value).then(() => { setEditing(false); r.reload(); }).catch((e) => setError(message(e))).finally(() => setSaving(false)); }; const publish = () => { setSaving(true); void api.publishAssignment(a.id).then(r.reload).catch((e) => setError(message(e))).finally(() => setSaving(false)); }; return <section><div className="page-heading"><div><a href={`#/classes/${a.class_id}`}>← Class</a><h1>{a.title}</h1><span className="badge">{a.status}</span></div>{a.status === "draft" && <div><button className="secondary" onClick={() => setEditing(!editing)}>Edit draft</button><button disabled={saving} onClick={publish}>Publish</button></div>}</div><Notice error={error}/>{editing ? <AssignmentForm initial={a} saving={saving} onSubmit={save}/> : <dl className="details"><dt>Topic</dt><dd>{a.topic}</dd><dt>Learning objective</dt><dd>{a.learning_objective}</dd><dt>Grade level</dt><dd>{a.grade_level}</dd><dt>Instructions</dt><dd>{a.instructions || "None"}</dd><dt>Sandbox type</dt><dd>Parameter explorer</dd><dt>Current status</dt><dd>{a.status}{a.published_at ? ` · published ${date(a.published_at)}` : ""}</dd></dl>}<section><h2>Student completion</h2><Notice error={submissions.error}/>{submissions.loading ? <Loading/> : submissions.data?.items.length ? <ul>{submissions.data.items.map((s) => <li key={s.submission_id}><strong>{s.student_name}</strong><span>{s.status} · {date(s.submitted_at)}</span></li>)}</ul> : <Empty>No submissions yet.</Empty>}</section></section>; }
